### ISSUE TITLE
Atualização arquivo txt

### ISSUE THREAD

**Issue by ShowmanBr** [williamdsw/saroo_configurations#2]
Depois da última atualização muitos desses jogos rodam sem alteração, você chegou a testar sem modificar o arquivo .txt?

**Comment by williamdsw** [comment]
Bomberman Wars testei ontem em live e roda perfeito sem modificações, já até atualizei no arquivo.
Street Fighter Alpha/Zero 3 testei também sem mas continua com bugs aqui, tive que colocar de volta nele.
Dos outros games faltam testes.
